(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Lin, Welcome to Coot version 0.8.9.2-pre")
(use-graphics-interface-state)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 12.60)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 0)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "/Library/Coot/share/coot/data/tutorial-modern.pdb" 1)
(make-and-draw-map "/Library/Coot/share/coot/data/rnasa-1.8-all_refmac1.mtz" "FWT" "PHWT" "" 0 0)
(make-and-draw-map "/Library/Coot/share/coot/data/rnasa-1.8-all_refmac1.mtz" "DELFWT" "PHDELWT" "" 0 1)
(setup-rotamers 1)
(setup-rotamers 0)
