filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Lin, Welcome to Coot version 0.8.9.2-pre")
use_graphics_interface_state ()
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (12.60)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (0)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("/Library/Coot/share/coot/data/tutorial-modern.pdb", 1)
make_and_draw_map ("/Library/Coot/share/coot/data/rnasa-1.8-all_refmac1.mtz", "FWT", "PHWT", "", 0, 0)
make_and_draw_map ("/Library/Coot/share/coot/data/rnasa-1.8-all_refmac1.mtz", "DELFWT", "PHDELWT", "", 0, 1)
setup_rotamers (1)
setup_rotamers (0)
